version: '3.8'

services:
  backend:
    image: backend-fastapi
    build:
      context: ./backend-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend-fastapi/app:/app/app
    environment:
      ML_SERVICE_URL: http://ml-model:3000
      MINIO_ENDPOINT_URL: http://192.168.1.11:9000
      DB_HOST: 192.168.1.11
      DB_USER: db_user
      DB_PASSWORD: password
      DB_PORT: 1521
      DB_SERVICE_NAME: freepdb1

  frontend:
    image: frontend-react
    build:
      context: ./frontend-react
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:8000

  ml-model:
    image: bento-clip:latest
    ports:
      - "3000:3000"

  # minio:
  #   image: minio/minio:latest
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - C:/MinIOData:/data
  #     - ${DIR_PATH}/minio-scripts/setup.sh:/usr/local/bin/setup.sh:ro
  #   command: server /data --console-address ":9001"

  # oracle-db:
  #   image: container-registry.oracle.com/database/free:latest-lite
  #   ports:
  #     - "1521:1521"
  #   environment:
  #     ORACLE_PWD: password
  #   volumes:
  #     - C:/oracle_data:/opt/oracle/oradata
  #     - ${DIR_PATH}/database-setup:/opt/oracle/scripts/startup
