version: '3.8'

services:
  backend:
    image: backend-fastapi
    build:
      context: ./backend-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - ml-model
      - minio
      - oracle-db
    environment:
      ML_SERVICE_URL: http://ml-model:3000
      MINIO_ENDPOINT_URL: http://minio:9000
      DB_HOST: oracle-db
      DB_USER: db_user
      DB_PASSWORD: password
      DB_PORT: 1521
      DB_SERVICE_NAME: freepdb1

  frontend:
    image: frontend-react
    build:
      context: ./frontend-react
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:8000

  ml-model:
    image: bento-clip:latest
    build:
      context: ./ml-model-service
    ports:
      - "3000:3000"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - C:/MinIOData:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-setup:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ${DIR_PATH}/minio-scripts/setup_buckets.sh:/setup.sh:ro
    entrypoint: /bin/sh /setup.sh
    environment:
      MINIO_ENDPOINT: http://minio:9000

  oracle-db:
    image: container-registry.oracle.com/database/free:latest-lite
    ports:
      - "1521:1521"
    volumes:
      - C:/oracle_data:/opt/oracle/oradata
      - ${DIR_PATH}/database-setup:/opt/oracle/scripts/startup
