BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE PRODUCT_IMAGE_EMBEDDINGS CASCADE CONSTRAINTS';
    EXCEPTION
        WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE USER_UPLOADED_IMAGE_EMBEDDINGS CASCADE CONSTRAINTS';
    EXCEPTION
        WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE '
    CREATE TABLE PRODUCT_IMAGE_EMBEDDINGS (
        image_id VARCHAR2(255) PRIMARY KEY,
        embedding VECTOR(512, FLOAT32)
    )';

    EXECUTE IMMEDIATE '
    CREATE TABLE USER_UPLOADED_IMAGE_EMBEDDINGS (
        image_id VARCHAR2(255) PRIMARY KEY,
        embedding VECTOR(512, FLOAT32)
    )';

    EXECUTE IMMEDIATE '
    CREATE VECTOR INDEX PRODUCT_IMAGE_IVF_INDEX ON PRODUCT_IMAGE_EMBEDDINGS(embedding)
    ORGANIZATION NEIGHBOR PARTITIONS
    DISTANCE COSINE
    WITH TARGET ACCURACY 95
    PARAMETERS (type IVF, neighbor partitions 600)';
END;
/