name: Microservices Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.ci.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "frontend"
          test-command: "curl -v -X POST -F 'items=@/app/public/mock-images/anime.png' http://ml-model:3000/encode_image"
